version: "3.1"

services: 
    php: 
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 80:80
        volumes: 
            - ./src:/var/www/html

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: always
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: db
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_NAME: mysql
        volumes:
            - ./db:/var/lib/mysql    

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080